ALTER TABLE cars ADD COLUMN po_official INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN po_8891 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN po_facebook INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN po_post_helper INTEGER NOT NULL DEFAULT 0;
